import { api } from './client';

export const resources = {
  dashboard: () => api.get('/dashboard'),
  patients: () => api.get('/patients?limit=500'),
  createPatient: (body) => api.post('/patients', body),
  updatePatient: (id, body) => api.put(`/patients/${id}`, body),
  deletePatient: (id) => api.delete(`/patients/${id}`),
  appointments: () => api.get('/appointments'),
  createAppointment: (body) => api.post('/appointments', body),
  updateAppointment: (id, body) => api.put(`/appointments/${id}`, body),
  deleteAppointment: (id) => api.delete(`/appointments/${id}`),
  services: () => api.get('/services?is_active=1'),
  payments: () => api.get('/payments'),
  createPayment: (body) => api.post('/payments', body),
  addPayment: (id, body) => api.post(`/payments/${id}/transaction`, body),
  deletePayment: (id) => api.delete(`/payments/${id}`),
  reminders: () => api.get('/reminders'),
  notifications: () => api.get('/notifications'),
  markNotificationRead: (id) => api.put(`/notifications/${encodeURIComponent(id)}/read`, {}),
  createReminder: (body) => api.post('/reminders', body),
  markReminderSent: (id) => api.put(`/reminders/${id}/send`, {}),
  deleteReminder: (id) => api.delete(`/reminders/${id}`),
  clinical: () => api.get('/clinical'),
  followUps: () => api.get('/follow-ups'),
  createFollowUp: (body) => api.post('/follow-ups', body),
  submitFollowUp: (id, body) => api.post(`/follow-ups/${id}/responses`, body),
  reviewFollowUp: (id, body) => api.put(`/follow-ups/${id}/review`, body),
  odontogram: (patientId) => api.get(`/odontogram/${patientId}`),
  saveOdontogram: (body) => api.post('/odontogram', body),
  updateOdontogram: (id, body) => api.put(`/odontogram/${id}`, body),
  deleteOdontogram: (id) => api.delete(`/odontogram/${id}`),
};
