import { StyleSheet } from 'react-native';
import { colors } from './theme/palette';

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    overflow: 'hidden',
  },
  authRoot: {
    flex: 1,
    overflow: 'hidden',
  },
  authScroll: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 34,
    paddingBottom: 34,
  },
  authTopBar: {
    alignItems: 'flex-end',
    minHeight: 40,
  },
  authLogoCard: {
    width: 104,
    height: 104,
    borderRadius: 30,
    borderCurve: 'continuous',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    boxShadow: '0 16px 50px rgba(37,99,235,0.18)',
  },
  authLogo: {
    width: 72,
    height: 72,
  },
  authTitleWrap: {
    alignItems: 'center',
    marginTop: 26,
    marginBottom: 26,
  },
  centerBrand: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  authBrandHealthy: {
    fontSize: 33,
    fontWeight: '900',
    letterSpacing: 0,
  },
  authBrandReminder: {
    fontSize: 33,
    fontWeight: '900',
    letterSpacing: 0,
    color: colors.purple,
  },
  authSubtitle: {
    fontSize: 16,
    marginTop: 6,
    fontWeight: '500',
  },
  segment: {
    height: 60,
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 4,
    marginBottom: 30,
    borderCurve: 'continuous',
  },
  segmentItem: {
    flex: 1,
    borderRadius: 24,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentText: {
    fontSize: 15,
    fontWeight: '800',
  },
  segmentLine: {
    position: 'absolute',
    bottom: 0,
    width: '72%',
    height: 3,
    borderRadius: 999,
    backgroundColor: colors.blue,
  },
  formBlock: {
    gap: 18,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
  screenSubtitle: {
    fontSize: 16,
    marginTop: -12,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '800',
  },
  inputShell: {
    minHeight: 58,
    borderWidth: 1,
    borderRadius: 16,
    borderCurve: 'continuous',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 12,
  },
  inputShellMultiline: {
    alignItems: 'flex-start',
    paddingTop: 4,
    paddingBottom: 4,
  },
  inputIcon: {
    fontSize: 14,
    fontWeight: '800',
    width: 38,
    textAlign: 'center',
    marginTop: 1,
    lineHeight: 18,
  },
  inputIconMultiline: {
    marginTop: 17,
  },
  input: {
    flex: 1,
    fontSize: 16,
    minHeight: 50,
    paddingVertical: 0,
    lineHeight: 22,
  },
  inputMultiline: {
    minHeight: 88,
    paddingTop: 13,
    paddingBottom: 13,
    textAlignVertical: 'top',
  },
  inputAction: {
    fontSize: 12,
    fontWeight: '900',
  },
  inputError: {
    color: colors.red,
    fontSize: 12,
    fontWeight: '800',
  },
  forgotText: {
    color: colors.blue,
    fontWeight: '800',
    fontSize: 14,
  },
  gradientButton: {
    minHeight: 60,
    borderRadius: 17,
    borderCurve: 'continuous',
    backgroundColor: colors.blue,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 18,
    boxShadow: '0 14px 32px rgba(59,130,246,0.30)',
  },
  ledButtonFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    opacity: 0.96,
  },
  gradientGlow: {
    position: 'absolute',
    left: 40,
    top: -30,
    width: 110,
    height: 110,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  ledButtonShimmer: {
    position: 'absolute',
    top: -30,
    bottom: -30,
    width: 54,
    backgroundColor: 'rgba(255,255,255,0.23)',
  },
  gradientLabel: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '900',
    zIndex: 1,
  },
  gradientArrowBubble: {
    minWidth: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  buttonArrowIcon: {
    width: 18,
    height: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonArrowLine: {
    position: 'absolute',
    left: 1,
    width: 14,
    height: 2.4,
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  buttonArrowHead: {
    position: 'absolute',
    right: 1,
    width: 8,
    height: 8,
    borderTopWidth: 2.4,
    borderRightWidth: 2.4,
    borderColor: '#ffffff',
    transform: [{ rotate: '45deg' }],
  },
  gradientArrow: {
    color: '#ffffff',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 24,
    zIndex: 1,
  },
  tipCard: {
    marginTop: 30,
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  tipTitle: {
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 5,
  },
  tipCopy: {
    fontSize: 14,
    lineHeight: 21,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoImage: {
    width: 56,
    height: 56,
  },
  brandLine: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  brandHealthy: {
    fontSize: 24,
    fontWeight: '900',
  },
  brandReminder: {
    fontSize: 24,
    fontWeight: '900',
    color: colors.purple,
  },
  brandSub: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  orb: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.58,
  },
  iconBadge: {
    borderRadius: 16,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    fontWeight: '900',
    fontSize: 16,
  },
  headerButton: {
    borderWidth: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  headerButtonText: {
    fontSize: 12,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  appHeader: {
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderRadius: 16,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 10px 20px rgba(59,130,246,0.12)',
  },
  backIcon: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIconLine: {
    position: 'absolute',
    left: 2,
    width: 14,
    height: 3,
    borderRadius: 999,
  },
  backIconLineTop: {
    transform: [{ rotate: '-45deg' }, { translateY: -4 }],
  },
  backIconLineBottom: {
    transform: [{ rotate: '45deg' }, { translateY: 4 }],
  },
  headerTitle: {
    fontSize: 21,
    fontWeight: '900',
  },
  headerMeta: {
    fontSize: 12,
    marginTop: 2,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  roundButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundButtonText: {
    fontSize: 15,
    fontWeight: '900',
  },
  bellIcon: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellHandle: {
    position: 'absolute',
    top: 2,
    width: 8,
    height: 5,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  bellDome: {
    position: 'absolute',
    top: 6,
    width: 15,
    height: 13,
    borderWidth: 2,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomWidth: 0,
  },
  bellBase: {
    position: 'absolute',
    bottom: 4,
    width: 18,
    height: 2,
    borderRadius: 999,
  },
  bellClapper: {
    position: 'absolute',
    bottom: 1,
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  themeIcon: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sunIconCore: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
  },
  sunRay: {
    position: 'absolute',
    width: 3,
    height: 6,
    borderRadius: 999,
  },
  moonIcon: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    left: 3,
    top: 3,
  },
  moonCutout: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    left: 10,
    top: 1,
  },
  badge: {
    position: 'absolute',
    top: -5,
    right: -4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.pink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  content: {
    padding: 18,
    paddingBottom: 144,
    gap: 18,
  },
  welcomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  hello: {
    color: colors.blue,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 4,
  },
  bigTitle: {
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
  },
  mutedCopy: {
    fontSize: 15,
    lineHeight: 22,
  },
  heroCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    overflow: 'hidden',
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 5,
  },
  heroText: {
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 23,
  },
  heroSmall: {
    fontSize: 13,
    marginTop: 4,
    lineHeight: 19,
  },
  heroButton: {
    minHeight: 48,
    minWidth: 102,
    borderRadius: 14,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  statCard: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 16,
    minHeight: 150,
    justifyContent: 'space-between',
  },
  statValue: {
    fontSize: 28,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  statLabel: {
    fontSize: 13,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900',
  },
  sectionAction: {
    color: colors.blue,
    fontSize: 13,
    fontWeight: '900',
  },
  chartCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
  },
  barChart: {
    height: 170,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  barWrap: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  barTrack: {
    width: '100%',
    maxWidth: 26,
    height: 132,
    borderRadius: 999,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '100%',
    borderRadius: 999,
  },
  barLabel: {
    fontSize: 11,
    fontWeight: '800',
  },
  monthlyCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    gap: 18,
  },
  monthlySummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  monthlyTotal: {
    fontSize: 28,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  monthlyBadge: {
    minWidth: 58,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 9,
    alignItems: 'center',
  },
  monthlyBadgeText: {
    color: colors.green,
    fontSize: 13,
    fontWeight: '900',
  },
  monthlyBadgeValue: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: 1,
  },
  monthlyChart: {
    height: 164,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 9,
  },
  monthlyBarWrap: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
  },
  monthlyBarTrack: {
    width: '100%',
    maxWidth: 30,
    height: 132,
    borderRadius: 999,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  monthlyBarFill: {
    width: '100%',
    borderRadius: 999,
  },
  topServicesCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    gap: 15,
  },
  serviceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  serviceRank: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceRankText: {
    fontSize: 14,
    fontWeight: '900',
  },
  serviceInfo: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  serviceTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  serviceName: {
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  serviceCount: {
    fontSize: 14,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  serviceTrack: {
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
  },
  serviceFill: {
    height: '100%',
    borderRadius: 999,
  },
  serviceRevenue: {
    fontSize: 11,
    fontWeight: '700',
  },
  appointmentCard: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  appointmentServicePreview: {
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  appointmentPrice: {
    fontSize: 15,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  timeBlock: {
    width: 58,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeText: {
    fontSize: 13,
    fontWeight: '900',
  },
  timeline: {
    width: 3,
    height: 42,
    borderRadius: 999,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
  cardSub: {
    fontSize: 13,
    lineHeight: 19,
  },
  smallChip: {
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  screenActions: {
    flexDirection: 'row',
    gap: 12,
  },
  searchBox: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  searchIcon: {
    fontSize: 18,
    fontWeight: '900',
    width: 24,
    textAlign: 'center',
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    minHeight: 48,
  },
  addButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
  },
  patientCard: {
    borderWidth: 1,
    borderRadius: 21,
    borderCurve: 'continuous',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: {
    color: colors.blue,
    fontSize: 16,
    fontWeight: '900',
  },
  inlineChips: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  cardTime: {
    fontSize: 14,
    fontWeight: '900',
  },
  patientCardActions: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    minHeight: 72,
    gap: 10,
  },
  deletePatientButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trashIcon: {
    width: 18,
    height: 20,
    alignItems: 'center',
  },
  trashHandle: {
    position: 'absolute',
    top: 0,
    width: 7,
    height: 4,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: colors.red,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  trashLid: {
    position: 'absolute',
    top: 5,
    width: 16,
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.red,
  },
  trashCan: {
    position: 'absolute',
    top: 8,
    width: 13,
    height: 12,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: colors.red,
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 3,
    paddingTop: 2,
  },
  trashLine: {
    width: 1.5,
    height: 7,
    borderRadius: 999,
    backgroundColor: colors.red,
  },
  chevron: {
    fontSize: 22,
    fontWeight: '900',
  },
  dayRow: {
    gap: 10,
    paddingRight: 6,
  },
  calendarJumpCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  calendarJumpButton: {
    width: 58,
    height: 58,
    borderRadius: 19,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 12px 26px rgba(59,130,246,0.24)',
  },
  calendarJumpIcon: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  dayPill: {
    width: 64,
    height: 88,
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  dayName: {
    fontSize: 12,
    fontWeight: '900',
  },
  dayNum: {
    fontSize: 22,
    fontWeight: '900',
  },
  dayMonth: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  scheduleHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  miniAdd: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniAddText: {
    color: '#ffffff',
    fontSize: 23,
    fontWeight: '800',
  },
  clinicalHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  clinicalPatientSelect: {
    minHeight: 76,
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clinicalCountRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clinicalCountChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  clinicalCountText: {
    fontSize: 11,
    fontWeight: '900',
  },
  odontogramCard: {
    borderWidth: 1,
    borderRadius: 24,
    borderCurve: 'continuous',
    padding: 14,
    gap: 16,
  },
  conditionLegend: {
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
  },
  conditionLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  conditionLegendDot: {
    width: 12,
    height: 12,
    borderRadius: 4,
    borderWidth: 2,
  },
  conditionLegendText: {
    fontSize: 10,
    fontWeight: '900',
  },
  odontogramScrollContent: {
    paddingHorizontal: 6,
    paddingBottom: 4,
  },
  odontogramMouth: {
    width: 640,
    alignItems: 'center',
    gap: 10,
  },
  archLabel: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  archRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  toothItem: {
    width: 34,
    alignItems: 'center',
    gap: 5,
  },
  toothShape: {
    width: 29,
    height: 48,
    borderWidth: 2,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  toothShapeMolar: {
    width: 34,
    height: 52,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 9,
    borderBottomRightRadius: 9,
  },
  toothShapePremolar: {
    width: 31,
    height: 50,
  },
  toothShapeCanine: {
    width: 28,
    height: 53,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  toothShapeLower: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  toothShapeSelected: {
    borderColor: colors.blue,
    boxShadow: '0 0 16px rgba(59,130,246,0.36)',
  },
  toothGroove: {
    position: 'absolute',
    top: 10,
    width: 16,
    height: 2,
    borderRadius: 999,
    opacity: 0.8,
  },
  toothGrooveVertical: {
    position: 'absolute',
    top: 7,
    width: 2,
    height: 12,
    borderRadius: 999,
    opacity: 0.7,
  },
  toothMarker: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toothMarkerText: {
    fontSize: 9,
    fontWeight: '900',
  },
  toothNumber: {
    fontSize: 10,
    fontWeight: '900',
  },
  occlusalWrap: {
    width: '100%',
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  occlusalLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    borderRadius: 999,
  },
  occlusalText: {
    paddingHorizontal: 12,
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  teethBoard: {
    borderWidth: 1,
    borderRadius: 24,
    borderCurve: 'continuous',
    padding: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  toothButton: {
    width: 43,
    height: 43,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toothText: {
    fontSize: 12,
    fontWeight: '900',
  },
  conditionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  conditionChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  conditionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  noteCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    gap: 12,
  },
  clinicalNoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  clearToothButton: {
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearToothText: {
    fontSize: 12,
    fontWeight: '900',
  },
  clinicalRecordsCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    gap: 12,
  },
  clinicalRecordList: {
    gap: 10,
  },
  clinicalRecordRow: {
    minHeight: 76,
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clinicalRecordTooth: {
    width: 46,
    height: 46,
    borderRadius: 16,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clinicalRecordToothText: {
    fontSize: 15,
    fontWeight: '900',
  },
  clinicalDeleteButton: {
    width: 40,
    height: 40,
    borderRadius: 15,
    borderCurve: 'continuous',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteInput: {
    minHeight: 110,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    textAlignVertical: 'top',
    fontSize: 14,
  },
  payHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  paymentCard: {
    borderWidth: 1,
    borderRadius: 21,
    borderCurve: 'continuous',
    padding: 16,
    gap: 12,
  },
  paymentMetricRow: {
    flexDirection: 'row',
    gap: 12,
  },
  paymentMetricCard: {
    flex: 1,
    minHeight: 82,
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 15,
    justifyContent: 'center',
    gap: 5,
  },
  paymentMetricValue: {
    fontSize: 19,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  paymentFilterCard: {
    borderWidth: 1,
    borderRadius: 21,
    borderCurve: 'continuous',
    padding: 14,
    gap: 10,
  },
  paymentFilterButton: {
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  paymentFilterText: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: '900',
  },
  paymentFilterCount: {
    minWidth: 28,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  paymentFilterOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  paymentFilterOptionCount: {
    minWidth: 34,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  paymentTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  paymentAmount: {
    fontSize: 21,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  paymentRightStack: {
    alignItems: 'flex-end',
    gap: 6,
  },
  paymentStatusChip: {
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  paymentFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  paymentActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  paymentActionButton: {
    minHeight: 36,
    borderWidth: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentActionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  progressTrack: {
    height: 9,
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  paymentSummaryBand: {
    minHeight: 74,
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  paymentSummaryAmount: {
    fontSize: 22,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  paymentDetailHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  paymentDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  paymentDetailCell: {
    width: '48%',
    minHeight: 74,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 13,
    paddingVertical: 11,
    justifyContent: 'center',
  },
  paymentDetailValue: {
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 21,
  },
  paymentHistoryRow: {
    minHeight: 72,
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reminderCard: {
    borderWidth: 1,
    borderRadius: 21,
    borderCurve: 'continuous',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  reminderHeaderBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reminderFilterTop: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
  },
  reminderRefreshButton: {
    width: 54,
    height: 54,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reminderRefreshText: {
    fontSize: 18,
    fontWeight: '900',
  },
  reminderCardBody: {
    flex: 1,
    minWidth: 0,
    gap: 9,
  },
  reminderCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  reminderMessagePreview: {
    borderRadius: 16,
    borderCurve: 'continuous',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  reminderActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  reminderPrimaryAction: {
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reminderPrimaryActionText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  reminderSecondaryAction: {
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 14,
    borderCurve: 'continuous',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reminderSecondaryActionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  reminderAiButton: {
    minHeight: 56,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reminderAiIcon: {
    width: 38,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '900',
  },
  reminderAiText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '900',
  },
  reminderDetailHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  reminderMessageBox: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 15,
    gap: 8,
  },
  reminderMessageText: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  notificationRow: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  notificationBody: {
    flex: 1,
    minWidth: 0,
    gap: 7,
  },
  notificationAction: {
    alignSelf: 'flex-start',
    minHeight: 34,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationActionText: {
    fontSize: 12,
    fontWeight: '900',
  },
  notificationEmpty: {
    minHeight: 160,
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  chatRoot: {
    flex: 1,
  },
  chatContent: {
    padding: 18,
    paddingBottom: 140,
    gap: 12,
  },
  messageBubble: {
    maxWidth: '82%',
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  messageText: {
    fontSize: 14,
    lineHeight: 21,
  },
  composer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 74,
    borderTopWidth: 1,
    padding: 12,
    flexDirection: 'row',
    gap: 10,
  },
  composerInput: {
    flex: 1,
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 17,
    paddingHorizontal: 14,
    fontSize: 14,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
  },
  profileCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 18,
    gap: 12,
  },
  settingsHero: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  settingsHeroCompact: {
    alignItems: 'flex-start',
  },
  settingsTabsCard: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 8,
    gap: 6,
  },
  settingsTab: {
    minHeight: 52,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsTabIcon: {
    width: 28,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '900',
  },
  settingsTabText: {
    fontSize: 15,
    fontWeight: '900',
  },
  settingsPanel: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 16,
    gap: 16,
  },
  settingsPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  settingsPanelHeaderCompact: {
    alignItems: 'stretch',
  },
  settingsHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  settingsSaveButton: {
    minHeight: 46,
    minWidth: 96,
    borderRadius: 15,
  },
  settingsSaveButtonCompact: {
    width: '100%',
    minWidth: 0,
  },
  settingsLogoCard: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 14,
    gap: 13,
  },
  settingsLogoPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  settingsLogoPreview: {
    width: 74,
    height: 74,
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  settingsLogoImage: {
    width: '100%',
    height: '100%',
  },
  settingsLogoDefaultImage: {
    width: 52,
    height: 52,
  },
  settingsUploadButton: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 15,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  settingsTwoCol: {
    flexDirection: 'row',
    gap: 12,
  },
  settingsStackedFields: {
    flexDirection: 'column',
  },
  settingsHalfField: {
    flex: 1,
    minWidth: 0,
  },
  settingsFullField: {
    width: '100%',
  },
  settingsUserBand: {
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 15,
    gap: 4,
  },
  settingRow: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoutButton: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
  },
  logoutText: {
    color: colors.red,
    fontSize: 15,
    fontWeight: '900',
  },
  quickGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  quickButton: {
    flex: 1,
    minHeight: 54,
  },
  moreCard: {
    borderWidth: 1,
    borderRadius: 21,
    borderCurve: 'continuous',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  bottomNav: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    height: 68,
    borderRadius: 24,
    borderCurve: 'continuous',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 6,
    boxShadow: '0 12px 30px rgba(15,23,42,0.16)',
  },
  modalRoot: {
    flex: 1,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  navIcon: {
    width: 30,
    height: 30,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIconText: {
    fontSize: 12,
    fontWeight: '900',
  },
  navLabel: {
    fontSize: 10,
    fontWeight: '900',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    padding: 20,
    paddingBottom: 34,
    gap: 18,
    maxHeight: '88%',
  },
  sheetGrabber: {
    width: 44,
    height: 5,
    borderRadius: 999,
    alignSelf: 'center',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '900',
  },
  closeText: {
    fontSize: 20,
    fontWeight: '900',
  },
  sheetScroll: {
    flexGrow: 0,
  },
  sheetScrollContent: {
    gap: 15,
    paddingBottom: 14,
  },
  formSection: {
    gap: 12,
  },
  formSectionTitleWrap: {
    borderBottomWidth: 1,
    paddingBottom: 8,
    marginTop: 4,
  },
  formSectionTitle: {
    color: colors.blue,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  photoUploadCard: {
    borderWidth: 1,
    borderRadius: 20,
    borderCurve: 'continuous',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  photoBox: {
    width: 72,
    height: 72,
    borderRadius: 20,
    borderWidth: 1,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  photoIcon: {
    fontSize: 24,
    fontWeight: '900',
  },
  photoHint: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
  },
  patientPhotoPreview: {
    width: '100%',
    height: '100%',
  },
  photoActionSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    padding: 20,
    paddingBottom: 44,
    gap: 15,
  },
  photoLargePreview: {
    width: 132,
    height: 132,
    borderRadius: 28,
    borderCurve: 'continuous',
    alignSelf: 'center',
  },
  photoActionGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  photoActionButton: {
    flex: 1,
    minHeight: 82,
    borderWidth: 1,
    borderRadius: 19,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  photoActionIcon: {
    fontSize: 15,
    fontWeight: '900',
  },
  photoActionText: {
    fontSize: 14,
    fontWeight: '900',
  },
  photoRemoveButton: {
    minHeight: 50,
    borderWidth: 1,
    borderRadius: 16,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoRemoveText: {
    color: colors.red,
    fontSize: 14,
    fontWeight: '900',
  },
  choiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  choiceChip: {
    minHeight: 40,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceChipText: {
    fontSize: 12,
    fontWeight: '900',
  },
  selectShell: {
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 62,
  },
  selectValueWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  selectValue: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  selectMeta: {
    minWidth: 42,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 18,
  },
  selectChevron: {
    fontSize: 15,
    fontWeight: '900',
    width: 18,
    textAlign: 'right',
  },
  selectorBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  selectorSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    maxHeight: '76%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    padding: 20,
    paddingBottom: 44,
    gap: 14,
  },
  selectorSearchBox: {
    flex: 0,
  },
  selectorList: {
    flexGrow: 0,
  },
  selectorListContent: {
    gap: 10,
    paddingBottom: 10,
  },
  selectorRow: {
    minHeight: 58,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  selectorLabel: {
    fontSize: 15,
    fontWeight: '900',
  },
  selectorMeta: {
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
  },
  selectorEmpty: {
    minHeight: 76,
    borderWidth: 1,
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 16,
    justifyContent: 'center',
  },
  datePickerCard: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: '18%',
    borderWidth: 1,
    borderRadius: 24,
    borderCurve: 'continuous',
    padding: 18,
    gap: 16,
  },
  detailBand: {
    borderRadius: 18,
    borderCurve: 'continuous',
    padding: 16,
    gap: 4,
  },
  dangerButton: {
    minHeight: 56,
    borderRadius: 17,
    borderCurve: 'continuous',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  dangerButtonText: {
    color: colors.red,
    fontSize: 15,
    fontWeight: '900',
  },
  deleteConfirmWrap: {
    alignItems: 'center',
    gap: 14,
    paddingVertical: 12,
  },
  deleteWarningIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteWarningText: {
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  confirmActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  confirmButton: {
    minWidth: 116,
    minHeight: 54,
    borderWidth: 1,
    borderRadius: 16,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  confirmButtonText: {
    fontSize: 15,
    fontWeight: '900',
  },
  recordRoot: {
    gap: 16,
  },
  recordHero: {
    borderWidth: 1,
    borderRadius: 22,
    borderCurve: 'continuous',
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  recordAvatar: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  recordAvatarImage: {
    width: '100%',
    height: '100%',
  },
  recordAvatarText: {
    color: colors.blue,
    fontSize: 18,
    fontWeight: '900',
  },
  recordHeroText: {
    flex: 1,
    minWidth: 0,
  },
  recordName: {
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 25,
  },
  recordSubtitle: {
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 19,
    marginTop: 2,
  },
  recordSection: {
    gap: 12,
  },
  recordGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  recordField: {
    width: '48%',
    minHeight: 72,
    borderWidth: 1,
    borderRadius: 17,
    borderCurve: 'continuous',
    paddingHorizontal: 13,
    paddingVertical: 11,
    justifyContent: 'center',
  },
  recordFieldWide: {
    width: '100%',
  },
  recordLabel: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 5,
  },
  recordValue: {
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 20,
  },
  toast: {
    position: 'absolute',
    bottom: 96,
    alignSelf: 'center',
    maxWidth: '88%',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 11,
    boxShadow: '0 10px 22px rgba(0,0,0,0.18)',
  },
  toastText: {
    fontSize: 13,
    fontWeight: '900',
  },
});
