import { StyleSheet } from 'react-native';

export const patientStyles = StyleSheet.create({
  content: { padding: 18, paddingBottom: 138, gap: 16 },
  hero: { borderWidth: 1, borderRadius: 28, padding: 20, gap: 10, overflow: 'hidden' },
  eyebrow: { fontSize: 12, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' },
  title: { fontSize: 28, lineHeight: 34, fontWeight: '900' },
  subtitle: { fontSize: 14, lineHeight: 21 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  stat: { flexGrow: 1, flexBasis: 145, borderWidth: 1, borderRadius: 20, padding: 15, gap: 5 },
  statValue: { fontSize: 22, fontWeight: '900' },
  statLabel: { fontSize: 12, fontWeight: '700' },
  sectionTitle: { fontSize: 19, fontWeight: '900' },
  card: { borderWidth: 1, borderRadius: 22, padding: 16, gap: 10 },
  cardTitle: { fontSize: 16, fontWeight: '850' },
  cardCopy: { fontSize: 13, lineHeight: 19 },
  chip: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  chipText: { fontSize: 11, fontWeight: '900' },
  button: { minHeight: 44, borderRadius: 14, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center' },
  buttonText: { color: '#fff', fontSize: 13, fontWeight: '850' },
  outlineButton: { minHeight: 42, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  outlineText: { fontSize: 13, fontWeight: '800' },
  quick: { width: '48%', minHeight: 96, borderWidth: 1, borderRadius: 20, padding: 14, justifyContent: 'space-between' },
  quickIcon: { fontSize: 19, fontWeight: '900' },
  progressTrack: { height: 9, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  tabs: { flexDirection: 'row', gap: 7 },
  tab: { flex: 1, minHeight: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  tabText: { fontSize: 11, fontWeight: '800', textAlign: 'center' },
  timeline: { width: 12, alignItems: 'center', alignSelf: 'stretch' },
  timelineDot: { width: 11, height: 11, borderRadius: 6 },
  timelineLine: { width: 2, flex: 1, minHeight: 28 },
  toothGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  tooth: { width: 42, height: 48, borderWidth: 1.5, borderRadius: 13, alignItems: 'center', justifyContent: 'center', gap: 2 },
  toothNumber: { fontSize: 11, fontWeight: '900' },
  toothMark: { fontSize: 9, fontWeight: '800' },
  empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 20, padding: 24, alignItems: 'center', gap: 7 },
  modalRoot: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(2,6,23,0.55)' },
  modalCard: { maxHeight: '92%', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 20, paddingBottom: 34, gap: 16 },
  fieldLabel: { fontSize: 12, fontWeight: '800' },
  field: { minHeight: 50, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 15 },
  divider: { height: 1 },
  nav: { position: 'absolute', left: 12, right: 12, borderWidth: 1, borderRadius: 25, padding: 7, flexDirection: 'row', justifyContent: 'space-around' },
  navItem: { flex: 1, alignItems: 'center', gap: 4, paddingVertical: 7 },
  navIcon: { width: 29, height: 29, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  navIconText: { fontSize: 12, fontWeight: '900' },
  navLabel: { width: '100%', fontSize: 9, fontWeight: '800', textAlign: 'center' },
  header: { borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingBottom: 13 },
  headerTitle: { fontSize: 22, fontWeight: '900' },
  headerMeta: { fontSize: 11, marginTop: 2 },
  headerButton: { width: 42, height: 42, borderWidth: 1, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  badge: { position: 'absolute', top: -4, right: -4, minWidth: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  badgeText: { color: '#fff', fontSize: 9, fontWeight: '900' },
});
